package terraform.inputs


# Garden of eden.  Create a few resources
lineage0 = {
    "aws_autoscaling_group.lamb": {
        "arn": "",
        "availability_zones.#": "1",
        "availability_zones.3205754986": "us-west-1a",
        "default_cooldown": "",
        "desired_capacity": "4",
        "destroy": false,
        "destroy_tainted": false,
        "force_delete": "true",
        "health_check_grace_period": "300",
        "health_check_type": "ELB",
        "id": "",
        "launch_configuration": "kitten",
        "load_balancers.#": "",
        "max_size": "5",
        "metrics_granularity": "1Minute",
        "min_size": "1",
        "name": "lamb",
        "protect_from_scale_in": "false",
        "vpc_zone_identifier.#": "",
        "wait_for_capacity_timeout": "10m"
    },
    "aws_instance.puppy": {
        "ami": "ami-09b4b74c",
        "associate_public_ip_address": "",
        "availability_zone": "",
        "destroy": false,
        "destroy_tainted": false,
        "ebs_block_device.#": "",
        "ephemeral_block_device.#": "",
        "id": "",
        "instance_state": "",
        "instance_type": "t2.micro",
        "ipv6_addresses.#": "",
        "key_name": "",
        "network_interface_id": "",
        "placement_group": "",
        "private_dns": "",
        "private_ip": "",
        "public_dns": "",
        "public_ip": "",
        "root_block_device.#": "",
        "security_groups.#": "",
        "source_dest_check": "true",
        "subnet_id": "",
        "tenancy": "",
        "vpc_security_group_ids.#": ""
    },
    "aws_launch_configuration.kitten": {
        "associate_public_ip_address": "false",
        "destroy": false,
        "destroy_tainted": false,
        "ebs_block_device.#": "",
        "ebs_optimized": "",
        "enable_monitoring": "true",
        "id": "",
        "image_id": "ami-09b4b74c",
        "instance_type": "t2.micro",
        "key_name": "",
        "name": "kitten",
        "root_block_device.#": ""
    },
    "destroy": false
}

# Create, modify, and delelete resources
lineage1 = {
    "aws_autoscaling_group.lamb": {
        "destroy": false,
        "destroy_tainted": false,
        "max_size": "4"
    },
    "aws_instance.pony": {
        "ami": "ami-09b4b74c",
        "associate_public_ip_address": "",
        "availability_zone": "",
        "destroy": false,
        "destroy_tainted": false,
        "ebs_block_device.#": "",
        "ephemeral_block_device.#": "",
        "id": "",
        "instance_state": "",
        "instance_type": "t2.micro",
        "ipv6_addresses.#": "",
        "key_name": "",
        "network_interface_id": "",
        "placement_group": "",
        "private_dns": "",
        "private_ip": "",
        "public_dns": "",
        "public_ip": "",
        "root_block_device.#": "",
        "security_groups.#": "",
        "source_dest_check": "true",
        "subnet_id": "",
        "tenancy": "",
        "vpc_security_group_ids.#": ""
    },
    "aws_instance.puppy": {
        "destroy": true,
        "destroy_tainted": false
    },
    "destroy": false
}

# Create several resources
large_create = {
    "aws_autoscaling_group.my_asg": {
        "arn": "",
        "availability_zones.#": "1",
        "availability_zones.3205754986": "us-west-1a",
        "default_cooldown": "",
        "desired_capacity": "4",
        "destroy": false,
        "destroy_tainted": false,
        "force_delete": "true",
        "health_check_grace_period": "300",
        "health_check_type": "ELB",
        "id": "",
        "launch_configuration": "my_web_config",
        "load_balancers.#": "",
        "max_size": "5",
        "metrics_granularity": "1Minute",
        "min_size": "1",
        "name": "my_asg",
        "protect_from_scale_in": "false",
        "vpc_zone_identifier.#": "",
        "wait_for_capacity_timeout": "10m"
    },
    "aws_autoscaling_group.my_asg2": {
        "arn": "",
        "availability_zones.#": "1",
        "availability_zones.2487133097": "us-west-2a",
        "default_cooldown": "",
        "desired_capacity": "4",
        "destroy": false,
        "destroy_tainted": false,
        "force_delete": "true",
        "health_check_grace_period": "300",
        "health_check_type": "ELB",
        "id": "",
        "launch_configuration": "my_web_config",
        "load_balancers.#": "",
        "max_size": "6",
        "metrics_granularity": "1Minute",
        "min_size": "1",
        "name": "my_asg2",
        "protect_from_scale_in": "false",
        "vpc_zone_identifier.#": "",
        "wait_for_capacity_timeout": "10m"
    },
    "aws_autoscaling_group.my_asg3": {
        "arn": "",
        "availability_zones.#": "1",
        "availability_zones.221770259": "us-west-2b",
        "default_cooldown": "",
        "desired_capacity": "4",
        "destroy": false,
        "destroy_tainted": false,
        "force_delete": "true",
        "health_check_grace_period": "300",
        "health_check_type": "ELB",
        "id": "",
        "launch_configuration": "my_web_config",
        "load_balancers.#": "",
        "max_size": "7",
        "metrics_granularity": "1Minute",
        "min_size": "1",
        "name": "my_asg3",
        "protect_from_scale_in": "false",
        "vpc_zone_identifier.#": "",
        "wait_for_capacity_timeout": "10m"
    },
    "aws_instance.web": {
        "ami": "ami-09b4b74c",
        "associate_public_ip_address": "",
        "availability_zone": "",
        "destroy": false,
        "destroy_tainted": false,
        "ebs_block_device.#": "",
        "ephemeral_block_device.#": "",
        "id": "",
        "instance_state": "",
        "instance_type": "t2.micro",
        "ipv6_addresses.#": "",
        "key_name": "",
        "network_interface_id": "",
        "placement_group": "",
        "private_dns": "",
        "private_ip": "",
        "public_dns": "",
        "public_ip": "",
        "root_block_device.#": "",
        "security_groups.#": "",
        "source_dest_check": "true",
        "subnet_id": "",
        "tenancy": "",
        "vpc_security_group_ids.#": ""
    },
    "aws_launch_configuration.my_web_config": {
        "associate_public_ip_address": "false",
        "destroy": false,
        "destroy_tainted": false,
        "ebs_block_device.#": "",
        "ebs_optimized": "",
        "enable_monitoring": "true",
        "id": "",
        "image_id": "ami-09b4b74c",
        "instance_type": "t2.micro",
        "key_name": "",
        "name": "my_web_config",
        "root_block_device.#": ""
    },
    "destroy": false
}
